project:
  type: website
  output-dir: ./docs
  
# Set language
lang: en

# Set bibliography source
bibliography: bibliography.bib

# Set website config and logos
website:
  title: "inrae-project-website"
  ## Navbar menu
  navbar:
    logo:  images/project-logo.jpg
    left:
      - href: index.qmd
        text: Home
        icon: house-door-fill
      - text: About the project
        icon: house-add-fill
        menu: 
          - text: About the project
            href: about.qmd
          - text: "Workpackage 1"
            href: workpackage1.qmd
          - text: "Workpackage 2"
            href: workpackage2.qmd
      - href: events.qmd
        text: Events
        icon: newspaper
      - href: publications.qmd
        text: Publications
        icon: book
      - href: partners.qmd
        text: Partners & Sponsors
        icon: link
    right:
      - text: "Source"
        icon: git
        href: https://github.com/
      - text: "Other links"
        icon: book
        menu: 
          - text: Quarto
            href: https://quarto.org
          - text: "INRAE"
            href: https://www.inrae.fr/
  ## Footer
  page-footer:
    left: |
        [![](images/Logo-INRAE.jpg){width=200px}](https://www.inrae.fr/)
    right: |
        ![](images/lab-logo.png){width=200px}
    center: 
      - text: Legal notice
        icon: scale-balanced
        href: legal_notice.qmd
      
 